manifest:
  package: rew.logger
  private: false
exec:
  entry: main.coffee
  default: default.coffee
  usage: usage.coffee
assets:
  icon: assets/icon.png
  folder: ./assets
install:
  requirements: []
